dist: focal

jobs:
  include:
  - name: Kong CE 2.7.x
    env: KONG_VERSION=2.7.x
  - name: Kong CE 2.8.x
    env: KONG_VERSION=2.8.x
  # - name: Kong CE master
  #   env: KONG_VERSION=nightly POSTGRES=latest CASSANDRA=latest

install:
- git clone --single-branch https://github.com/Kong/kong-pongo ../kong-pongo
- "../kong-pongo/pongo.sh up"
- "../kong-pongo/pongo.sh build"

script:
- "../kong-pongo/pongo.sh lint"
- "../kong-pongo/pongo.sh run"
