name: Lint

on:
  push:

jobs:
  luacheck:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip-ci]') }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: LuaCheck linter
      uses: lunarmodules/luacheck@master
