name: Generate release message

on:
  workflow_dispatch:

jobs:
  releasePlugin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare release
        run: |
          cat <<EOF > /tmp/release-message.md
          # Changes in this release
          \$(git log \$(git describe --tags --abbrev=0)..HEAD --oneline)
          EOF
