name: Testing plugin release
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        decription: "Release version"
        required: false


jobs:
  releasePlugin:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: leafo/gh-actions-lua@v9
    - uses: leafo/gh-actions-luarocks@v4

    - name: Install locally
      env:
        PLUGIN_RELEASE_VERSION: ${{ github.event.inputs.releaseVersion }}
      run: |
        luarocks install --local kong-plugin-tag-executor-*.rockspec
        luarocks show kong-plugin-tag-executor
        luarocks new_version kong-plugin-tag-executor-*.rockspec $PLUGIN_RELEASE_VERSION
        ls -la
