name: Testing plugin release

on:
  workflow_dispatch:
    inputs:
      bumpVersion:
        decription: |
          Bump to this version after release.
          If left empty will bump revision only
        required: false

jobs:
  releasePlugin:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: leafo/gh-actions-lua@v9
    - uses: leafo/gh-actions-luarocks@v4

    - name: Install locally
      run: |
        SPEC_FILE=$(ls kong-plugin-tag-executor-*.rockspec)
        alias plug_version='luarocks show kong-plugin-tag-executor | grep kong-plugin-tag-executor | head -n 1 | cut -d" " -f 2'
        luarocks install --local $SPEC_FILE
    - name: Release plugin
      run: |
        RELEASE_VERSION=$(plug_version)
        luarocks upload --api-key aahaha $SPEC_FILE || echo "fail"
    - name: Bump version
      env:
        INPUT_VERSION: ${{ github.event.inputs.releaseVersion }}
      run:
        luarocks new_version $SPEC_FILE $INPUT_VERSION
        rm $SPEC_FILE
        SPEC_FILE=$(ls kong-plugin-tag-executor-*.rockspec)
        luarocks install --local $SPEC_FILE
        NEW_VERSION=$(plug_version)
        echo 'New version: $NEW_VERSION'
        ls -la
