name: Test

on:
  workflow_run:
    workflows: ["Lint"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, '[skip-ci]') &&
      github.event.workflow_run.conclusion == 'success'

    strategy:
      fail-fast: true
      matrix:
        kongVersion:
          - "2.7.x"
          - "2.8.x"
          - "3.3.x"
          - "dev"

    steps:
      - uses: actions/checkout@v3

      - uses: Kong/kong-pongo-action@latest
        with:
          kong_version: ${{ matrix.kongVersion }}

      - run: pongo run -- --coverage

      - uses: leafo/gh-actions-lua@v8
        if: success()
      - uses: leafo/gh-actions-luarocks@v4
        if: success()
