name: "Test"

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip-ci]') }}

    strategy:
      fail-fast: true
      matrix:
        kongVersion:
        - "2.7.x"
        - "2.8.x"
        - "nightly"

    steps:
    - uses: actions/checkout@v3

    - uses: Kong/kong-pongo-action@v1
      with:
        kong_version: ${{ matrix.kongVersion }}

    - run: pongo run -- --coverage

    - uses: leafo/gh-actions-lua@v8
      if: success()
    - uses: leafo/gh-actions-luarocks@v4
      if: success()
